export interface MCQQuestion {
  question: string;
  options: string[];
  correctIndex: number;
}

const pythonQuestions: MCQQuestion[] = [
  { question: "What is the output of the following code?\n\nx = [1, 2, 3]\nprint(x * 2)", options: ["[1, 2, 3, 1, 2, 3]", "[2, 4, 6]", "Error", "[1, 2, 3, 2]"], correctIndex: 0 },
  { question: "What does the following code print?\n\ndef foo(a, b=[]):\n    b.append(a)\n    return b\n\nprint(foo(1))\nprint(foo(2))", options: ["[1] [2]", "[1] [1, 2]", "Error", "[1, 2] [1, 2]"], correctIndex: 1 },
  { question: "What is the output?\n\nprint(type(3/2))", options: ["<class 'int'>", "<class 'float'>", "<class 'double'>", "Error"], correctIndex: 1 },
  { question: "Fill in the blank to create a dictionary comprehension:\n\nresult = {_____ for x in range(5)}", options: ["x: x**2", "x, x**2", "(x, x**2)", "x = x**2"], correctIndex: 0 },
  { question: "What is the output?\n\nprint('hello'[::-1])", options: ["hello", "olleh", "h", "Error"], correctIndex: 1 },
  { question: "Which keyword is used to create a generator in Python?", options: ["return", "yield", "generate", "iter"], correctIndex: 1 },
  { question: "What is the output?\n\na = {1, 2, 3}\nb = {2, 3, 4}\nprint(a & b)", options: ["{1, 4}", "{2, 3}", "{1, 2, 3, 4}", "Error"], correctIndex: 1 },
  { question: "Fill in the blank to handle an exception:\n\ntry:\n    x = 1/0\n_____ ZeroDivisionError:\n    print('Error')", options: ["catch", "except", "handle", "rescue"], correctIndex: 1 },
  { question: "What is the output?\n\nprint(bool(''), bool('0'), bool(0))", options: ["False True False", "False False False", "True True False", "False True True"], correctIndex: 0 },
  { question: "What does `lambda x: x + 1` create?", options: ["A named function", "An anonymous function", "A class", "A decorator"], correctIndex: 1 },
  { question: "What is the output?\n\nx = 'Python'\nprint(x[1:4])", options: ["Pyt", "yth", "ytho", "Python"], correctIndex: 1 },
  { question: "Which method removes and returns the last element of a list?", options: ["remove()", "pop()", "delete()", "discard()"], correctIndex: 1 },
  { question: "What is the output?\n\nprint(2 ** 3 ** 2)", options: ["64", "512", "8", "None"], correctIndex: 1 },
  { question: "Fill in the blank to read a file:\n\nwith _____(file, 'r') as f:\n    data = f.read()", options: ["read", "open", "file", "load"], correctIndex: 1 },
  { question: "What is the output?\n\nprint([i for i in range(10) if i % 3 == 0])", options: ["[0, 3, 6, 9]", "[3, 6, 9]", "[0, 3, 6]", "[1, 4, 7]"], correctIndex: 0 },
  { question: "What does `__init__` method do in a Python class?", options: ["Destroys the object", "Initializes the object", "Returns the object type", "Copies the object"], correctIndex: 1 },
  { question: "What is the output?\n\nx = {'a': 1, 'b': 2}\nprint(x.get('c', 0))", options: ["None", "Error", "0", "c"], correctIndex: 2 },
  { question: "Which module is used for regular expressions in Python?", options: ["regex", "re", "regexp", "pattern"], correctIndex: 1 },
  { question: "What is the output?\n\nprint(list(map(str, [1, 2, 3])))", options: ["[1, 2, 3]", "['1', '2', '3']", "Error", "('1', '2', '3')"], correctIndex: 1 },
  { question: "What is the difference between `is` and `==` in Python?", options: ["`is` compares values, `==` compares identity", "`is` compares identity, `==` compares values", "They are the same", "`is` is for strings only"], correctIndex: 1 },
];

const javaQuestions: MCQQuestion[] = [
  { question: "What is the output?\n\nString s = \"Hello\";\ns.concat(\" World\");\nSystem.out.println(s);", options: ["Hello World", "Hello", "Error", "null"], correctIndex: 1 },
  { question: "Which keyword is used to inherit a class in Java?", options: ["implements", "extends", "inherits", "super"], correctIndex: 1 },
  { question: "What is the output?\n\nint[] arr = {1, 2, 3};\nSystem.out.println(arr.length);", options: ["2", "3", "4", "Error"], correctIndex: 1 },
  { question: "Fill in the blank to create an interface:\n\n_____ Printable {\n    void print();\n}", options: ["class", "abstract", "interface", "struct"], correctIndex: 2 },
  { question: "What is the output?\n\nSystem.out.println(10 + 20 + \"Hello\");", options: ["1020Hello", "30Hello", "Hello1020", "Error"], correctIndex: 1 },
  { question: "Which collection does not allow duplicate elements?", options: ["ArrayList", "LinkedList", "HashSet", "Vector"], correctIndex: 2 },
  { question: "What is the output?\n\nint x = 5;\nSystem.out.println(x++ + ++x);", options: ["10", "12", "11", "13"], correctIndex: 1 },
  { question: "What is the purpose of the `final` keyword?", options: ["Makes a variable constant", "Ends a loop", "Handles exceptions", "Creates abstract classes"], correctIndex: 0 },
  { question: "Fill in the blank for exception handling:\n\ntry {\n    int x = 1/0;\n} _____ (ArithmeticException e) {\n    System.out.println(e);\n}", options: ["except", "catch", "handle", "rescue"], correctIndex: 1 },
  { question: "What is autoboxing in Java?", options: ["Converting String to int", "Automatic conversion between primitive and wrapper types", "Creating objects automatically", "Memory management"], correctIndex: 1 },
  { question: "What is the output?\n\nString a = new String(\"Hello\");\nString b = new String(\"Hello\");\nSystem.out.println(a == b);", options: ["true", "false", "Error", "null"], correctIndex: 1 },
  { question: "Which access modifier makes a member visible only within its class?", options: ["public", "protected", "private", "default"], correctIndex: 2 },
  { question: "What is the output?\n\nint[] a = {1,2,3};\nint[] b = a;\nb[0] = 10;\nSystem.out.println(a[0]);", options: ["1", "10", "Error", "0"], correctIndex: 1 },
  { question: "What does the `static` keyword mean in Java?", options: ["Member belongs to the class, not instance", "Variable cannot change", "Method is abstract", "Class cannot be inherited"], correctIndex: 0 },
  { question: "Which method must be implemented when implementing Runnable?", options: ["start()", "run()", "execute()", "main()"], correctIndex: 1 },
  { question: "What is the output?\n\nSystem.out.println(\"Hello\" + \"World\" == \"HelloWorld\");", options: ["true", "false", "Error", "null"], correctIndex: 0 },
  { question: "What is a constructor in Java?", options: ["A method that returns an object", "A special method called when creating objects", "A static method", "A final method"], correctIndex: 1 },
  { question: "Fill in the blank for a for-each loop:\n\nfor (int x _____ arr) {\n    System.out.println(x);\n}", options: ["in", ":", "of", "from"], correctIndex: 1 },
  { question: "What is method overloading?", options: ["Same method name, different parameters", "Same method name, same parameters", "Overriding parent method", "Creating abstract methods"], correctIndex: 0 },
  { question: "What is the output?\n\nArrayList<Integer> list = new ArrayList<>();\nlist.add(1);\nlist.add(2);\nlist.remove(0);\nSystem.out.println(list);", options: ["[2]", "[1]", "[1, 2]", "Error"], correctIndex: 0 },
];

const cppQuestions: MCQQuestion[] = [
  { question: "What is the output?\n\n#include <iostream>\nusing namespace std;\nint main() {\n    int x = 10;\n    cout << x++ << \" \" << ++x;\n}", options: ["10 12", "10 11", "11 12", "Undefined behavior"], correctIndex: 3 },
  { question: "Which operator is used for dynamic memory allocation in C++?", options: ["malloc", "alloc", "new", "create"], correctIndex: 2 },
  { question: "What is the output?\n\nint arr[] = {1, 2, 3, 4, 5};\ncout << sizeof(arr)/sizeof(arr[0]);", options: ["5", "4", "20", "1"], correctIndex: 0 },
  { question: "Fill in the blank for a reference variable:\n\nint x = 10;\nint _____ y = x;", options: ["*", "&", "^", "ref"], correctIndex: 1 },
  { question: "What is the output?\n\nstring s = \"Hello\";\ncout << s.substr(1, 3);", options: ["Hel", "ell", "ello", "He"], correctIndex: 1 },
  { question: "What is a virtual function used for?", options: ["Memory management", "Runtime polymorphism", "Compile-time optimization", "Exception handling"], correctIndex: 1 },
  { question: "What is the output?\n\nvector<int> v = {1, 2, 3};\nv.push_back(4);\ncout << v.size();", options: ["3", "4", "5", "Error"], correctIndex: 1 },
  { question: "Which keyword prevents a class from being inherited?", options: ["static", "const", "final", "sealed"], correctIndex: 2 },
  { question: "What is the output?\n\nint *p = new int(5);\ncout << *p;\ndelete p;", options: ["5", "0", "Error", "Garbage"], correctIndex: 0 },
  { question: "What is RAII in C++?", options: ["Random Access Indexed Array", "Resource Acquisition Is Initialization", "Runtime Application Interface", "Recursive Algorithm Implementation"], correctIndex: 1 },
  { question: "Fill in the blank:\n\nclass Dog : _____ Animal {\n};", options: ["extends", "implements", "public", "inherits"], correctIndex: 2 },
  { question: "What is the output?\n\nmap<string, int> m;\nm[\"a\"] = 1;\nm[\"b\"] = 2;\ncout << m.size();", options: ["0", "1", "2", "Error"], correctIndex: 2 },
  { question: "What does `const` after a member function mean?", options: ["Function returns a constant", "Function doesn't modify the object", "Function is static", "Function cannot be overridden"], correctIndex: 1 },
  { question: "What is the output?\n\nint a = 5, b = 10;\nswap(a, b);\ncout << a << \" \" << b;", options: ["5 10", "10 5", "Error", "0 0"], correctIndex: 1 },
  { question: "What is a smart pointer?", options: ["A pointer that is faster", "An object that manages dynamically allocated memory", "A pointer to functions", "A constant pointer"], correctIndex: 1 },
  { question: "What is the output?\n\nauto x = 3.14;\ncout << typeid(x).name();", options: ["int", "float", "double (or 'd')", "auto"], correctIndex: 2 },
  { question: "Which STL container provides O(1) average insertion?", options: ["vector", "list", "unordered_map", "set"], correctIndex: 2 },
  { question: "What is the purpose of `template<typename T>`?", options: ["Type casting", "Generic programming", "Exception handling", "Memory management"], correctIndex: 1 },
  { question: "What is the output?\n\ntry {\n    throw 42;\n} catch (int e) {\n    cout << e;\n}", options: ["42", "Error", "0", "Nothing"], correctIndex: 0 },
  { question: "What is the difference between `struct` and `class` in C++?", options: ["No difference", "Default access: struct is public, class is private", "struct cannot have methods", "class cannot have public members"], correctIndex: 1 },
];

const webDevQuestions: MCQQuestion[] = [
  { question: "What is the output?\n\nconsole.log(typeof null);", options: ["'null'", "'undefined'", "'object'", "'boolean'"], correctIndex: 2 },
  { question: "Which CSS property is used to create a flex container?", options: ["display: block", "display: flex", "display: grid", "display: inline"], correctIndex: 1 },
  { question: "What is the output?\n\nconsole.log([] == false);", options: ["true", "false", "Error", "undefined"], correctIndex: 0 },
  { question: "Fill in the blank to select an element by ID:\n\ndocument._____('myId');", options: ["querySelector", "getElementById", "getElement", "selectById"], correctIndex: 1 },
  { question: "What does `async/await` do in JavaScript?", options: ["Creates threads", "Handles synchronous code", "Simplifies working with Promises", "Creates web workers"], correctIndex: 2 },
  { question: "What is the output?\n\nconst arr = [1, 2, 3];\nconst [a, ...rest] = arr;\nconsole.log(rest);", options: ["[1, 2, 3]", "[2, 3]", "[1]", "Error"], correctIndex: 1 },
  { question: "Which HTTP method is used to update a resource?", options: ["GET", "POST", "PUT", "DELETE"], correctIndex: 2 },
  { question: "What is the output?\n\nconsole.log('5' + 3);\nconsole.log('5' - 3);", options: ["8, 2", "'53', 2", "'53', '53'", "Error"], correctIndex: 1 },
  { question: "What does `position: sticky` do in CSS?", options: ["Fixes element to viewport", "Positions relative then fixed on scroll", "Makes element invisible", "Centers the element"], correctIndex: 1 },
  { question: "What is the Virtual DOM?", options: ["The actual browser DOM", "A lightweight copy of the DOM for efficient updates", "A CSS rendering engine", "A server-side DOM"], correctIndex: 1 },
  { question: "Fill in the blank for a React functional component:\n\nfunction App() {\n  const [count, setCount] = _____useState_____(0);\n  return <button onClick={() => setCount(count + 1)}>{count}</button>;\n}\n\nWhat hook is used?", options: ["useEffect", "useState", "useRef", "useMemo"], correctIndex: 1 },
  { question: "What is the output?\n\nconst obj = {a: 1, b: 2};\nconst {a, ...rest} = obj;\nconsole.log(rest);", options: ["{a: 1}", "{b: 2}", "{a: 1, b: 2}", "Error"], correctIndex: 1 },
  { question: "What does CORS stand for?", options: ["Cross-Origin Resource Sharing", "Cross-Object Reference System", "Client-Origin Request Service", "Cache-Optimized Resource System"], correctIndex: 0 },
  { question: "Which CSS unit is relative to the root element's font size?", options: ["em", "rem", "px", "vh"], correctIndex: 1 },
  { question: "What is the output?\n\nPromise.resolve(1)\n  .then(x => x + 1)\n  .then(x => console.log(x));", options: ["1", "2", "undefined", "Error"], correctIndex: 1 },
  { question: "What is the purpose of `useEffect` in React?", options: ["Manage state", "Handle side effects", "Create refs", "Memoize values"], correctIndex: 1 },
  { question: "What does `localStorage` do?", options: ["Stores data in cookies", "Stores key-value pairs in the browser permanently", "Stores data on the server", "Creates session variables"], correctIndex: 1 },
  { question: "What is the output?\n\nconst f = () => arguments;\nconsole.log(f(1, 2));", options: ["[1, 2]", "Error (arguments not defined in arrow functions)", "undefined", "{0: 1, 1: 2}"], correctIndex: 1 },
  { question: "Which HTML5 tag is used for navigation links?", options: ["<div>", "<nav>", "<header>", "<section>"], correctIndex: 1 },
  { question: "What is the output?\n\nconsole.log(0.1 + 0.2 === 0.3);", options: ["true", "false", "Error", "undefined"], correctIndex: 1 },
];

const dsaQuestions: MCQQuestion[] = [
  { question: "What is the time complexity of binary search?", options: ["O(n)", "O(log n)", "O(n log n)", "O(1)"], correctIndex: 1 },
  { question: "Which data structure uses FIFO principle?", options: ["Stack", "Queue", "Array", "Tree"], correctIndex: 1 },
  { question: "What is the output of an in-order traversal of a BST?", options: ["Random order", "Sorted ascending order", "Sorted descending order", "Level order"], correctIndex: 1 },
  { question: "What is the worst-case time complexity of QuickSort?", options: ["O(n log n)", "O(n)", "O(n²)", "O(log n)"], correctIndex: 2 },
  { question: "Which data structure is best for implementing a priority queue?", options: ["Array", "Linked List", "Heap", "Stack"], correctIndex: 2 },
  { question: "What is the space complexity of merge sort?", options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], correctIndex: 2 },
  { question: "Fill in the blank:\nA _____ is a tree where every node has at most two children.", options: ["Binary tree", "B-tree", "AVL tree", "Red-black tree"], correctIndex: 0 },
  { question: "What is the time complexity of inserting at the beginning of a linked list?", options: ["O(n)", "O(log n)", "O(1)", "O(n²)"], correctIndex: 2 },
  { question: "Which algorithm is used to find shortest path in an unweighted graph?", options: ["DFS", "BFS", "Dijkstra's", "Floyd-Warshall"], correctIndex: 1 },
  { question: "What is a hash collision?", options: ["Two keys mapping to the same index", "Memory overflow", "Stack overflow", "Null pointer"], correctIndex: 0 },
  { question: "What is the output of post-order traversal?\nTree: 1 (left: 2, right: 3)", options: ["1 2 3", "2 3 1", "2 1 3", "3 2 1"], correctIndex: 1 },
  { question: "Which sorting algorithm is stable?", options: ["QuickSort", "HeapSort", "Merge Sort", "Selection Sort"], correctIndex: 2 },
  { question: "What is dynamic programming?", options: ["Programming at runtime", "Breaking problems into overlapping subproblems", "Using dynamic arrays", "Compiling at runtime"], correctIndex: 1 },
  { question: "What is the time complexity of accessing an element by index in an array?", options: ["O(n)", "O(log n)", "O(1)", "O(n²)"], correctIndex: 2 },
  { question: "Which traversal uses a stack?", options: ["BFS", "DFS", "Level-order", "None"], correctIndex: 1 },
  { question: "What is an AVL tree?", options: ["A binary tree with no restrictions", "A self-balancing BST", "A tree with exactly two children per node", "A B-tree variant"], correctIndex: 1 },
  { question: "What is the amortized time complexity of ArrayList.add() in Java?", options: ["O(1)", "O(n)", "O(log n)", "O(n²)"], correctIndex: 0 },
  { question: "What does topological sorting require?", options: ["Undirected graph", "Directed Acyclic Graph (DAG)", "Complete graph", "Weighted graph"], correctIndex: 1 },
  { question: "What is the time complexity of building a heap from an array?", options: ["O(n log n)", "O(n)", "O(n²)", "O(log n)"], correctIndex: 1 },
  { question: "Which technique is used to detect a cycle in a linked list?", options: ["Binary search", "Two pointers (Floyd's)", "Hashing", "Both B and C"], correctIndex: 3 },
];

const dbQuestions: MCQQuestion[] = [
  { question: "What does SQL stand for?", options: ["Structured Query Language", "Simple Query Logic", "Standard Query Language", "Sequential Query Language"], correctIndex: 0 },
  { question: "Which SQL command is used to remove a table?", options: ["DELETE TABLE", "REMOVE TABLE", "DROP TABLE", "DESTROY TABLE"], correctIndex: 2 },
  { question: "What is normalization in databases?", options: ["Making data larger", "Reducing data redundancy", "Adding more tables", "Deleting duplicate rows"], correctIndex: 1 },
  { question: "Fill in the blank:\n\nSELECT * FROM users _____ age > 18;", options: ["IF", "WHERE", "WHEN", "HAVING"], correctIndex: 1 },
  { question: "What is a primary key?", options: ["Any column in a table", "A unique identifier for each row", "A foreign reference", "An index"], correctIndex: 1 },
  { question: "Which JOIN returns all rows from both tables?", options: ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"], correctIndex: 3 },
  { question: "What is ACID in databases?", options: ["A type of database", "Atomicity, Consistency, Isolation, Durability", "A query language", "A data type"], correctIndex: 1 },
  { question: "What does an INDEX do?", options: ["Stores backup data", "Speeds up data retrieval", "Encrypts data", "Compresses tables"], correctIndex: 1 },
  { question: "What is a foreign key?", options: ["A key from another database", "A column referencing another table's primary key", "An encrypted key", "A unique key"], correctIndex: 1 },
  { question: "Fill in the blank:\n\nSELECT COUNT(*) FROM orders _____ BY customer_id;", options: ["SORT", "ORDER", "GROUP", "FILTER"], correctIndex: 2 },
  { question: "What is a stored procedure?", options: ["A saved SQL query that can be executed repeatedly", "A data backup", "A table type", "A view"], correctIndex: 0 },
  { question: "What is the difference between DELETE and TRUNCATE?", options: ["No difference", "DELETE removes specific rows, TRUNCATE removes all rows", "TRUNCATE is slower", "DELETE drops the table"], correctIndex: 1 },
  { question: "What is a transaction?", options: ["A database table", "A sequence of operations treated as a single unit", "A query optimizer", "A data type"], correctIndex: 1 },
  { question: "Which command is used to add a new column?", options: ["ADD COLUMN", "ALTER TABLE ... ADD", "INSERT COLUMN", "CREATE COLUMN"], correctIndex: 1 },
  { question: "What is NoSQL?", options: ["No SQL allowed", "Non-relational database systems", "A SQL extension", "A programming language"], correctIndex: 1 },
  { question: "What is a VIEW in SQL?", options: ["A physical table", "A virtual table based on a query", "An index", "A stored procedure"], correctIndex: 1 },
  { question: "What does HAVING clause do?", options: ["Filters rows before grouping", "Filters groups after GROUP BY", "Sorts results", "Joins tables"], correctIndex: 1 },
  { question: "What is denormalization?", options: ["Removing all tables", "Adding redundancy for performance", "Normalizing twice", "Deleting indexes"], correctIndex: 1 },
  { question: "What is a composite key?", options: ["A key made of multiple columns", "An encrypted key", "A foreign key", "A surrogate key"], correctIndex: 0 },
  { question: "What is the CAP theorem?", options: ["Consistency, Availability, Partition tolerance — pick two", "Create, Alter, Partition", "A sorting algorithm", "A type of JOIN"], correctIndex: 0 },
];

const cloudQuestions: MCQQuestion[] = [
  { question: "What does IaaS stand for?", options: ["Internet as a Service", "Infrastructure as a Service", "Integration as a Service", "Information as a Service"], correctIndex: 1 },
  { question: "Which AWS service provides object storage?", options: ["EC2", "S3", "RDS", "Lambda"], correctIndex: 1 },
  { question: "What is a container in cloud computing?", options: ["A physical server", "A lightweight isolated environment for running applications", "A database", "A network switch"], correctIndex: 1 },
  { question: "What is serverless computing?", options: ["Computing without servers", "Cloud provider manages server infrastructure", "Computing without internet", "Local computing only"], correctIndex: 1 },
  { question: "What does Docker do?", options: ["Manages databases", "Containerizes applications", "Provides DNS services", "Manages SSL certificates"], correctIndex: 1 },
  { question: "What is Kubernetes used for?", options: ["Database management", "Container orchestration", "File storage", "Email services"], correctIndex: 1 },
  { question: "What is auto-scaling?", options: ["Manually adding servers", "Automatically adjusting resources based on demand", "Deleting unused servers", "Upgrading CPU"], correctIndex: 1 },
  { question: "Which service model provides complete applications?", options: ["IaaS", "PaaS", "SaaS", "FaaS"], correctIndex: 2 },
  { question: "What is a VPC?", options: ["Virtual Private Cloud — isolated network in the cloud", "Virtual Public Cloud", "Very Private Computer", "Virtual Processing Core"], correctIndex: 0 },
  { question: "What is a load balancer?", options: ["A storage device", "Distributes traffic across multiple servers", "A firewall", "A monitoring tool"], correctIndex: 1 },
  { question: "What is CI/CD?", options: ["Cloud Infrastructure/Cloud Deployment", "Continuous Integration/Continuous Deployment", "Container Integration/Container Delivery", "Code Inspection/Code Debugging"], correctIndex: 1 },
  { question: "What is a CDN?", options: ["Central Data Network", "Content Delivery Network", "Cloud Database Node", "Container Distribution Network"], correctIndex: 1 },
  { question: "What is microservices architecture?", options: ["One large application", "Small, independently deployable services", "A database pattern", "A testing framework"], correctIndex: 1 },
  { question: "What is AWS Lambda?", options: ["A virtual machine service", "A serverless compute service", "A storage service", "A database service"], correctIndex: 1 },
  { question: "What is the benefit of cloud computing?", options: ["Higher upfront costs", "Pay-as-you-go pricing and scalability", "Less security", "Slower deployment"], correctIndex: 1 },
  { question: "What is a region in cloud computing?", options: ["A data center location", "A programming language", "A database type", "A container"], correctIndex: 0 },
  { question: "What is DevOps?", options: ["A programming language", "Culture/practice combining development and operations", "A cloud provider", "A database tool"], correctIndex: 1 },
  { question: "What is object storage?", options: ["Storing physical objects", "Storing data as objects with metadata", "SQL storage", "File system storage"], correctIndex: 1 },
  { question: "What is Infrastructure as Code (IaC)?", options: ["Writing code on servers", "Managing infrastructure through code/scripts", "Building physical servers", "Coding in the cloud"], correctIndex: 1 },
  { question: "What is a multi-cloud strategy?", options: ["Using one cloud provider", "Using services from multiple cloud providers", "Cloud backup only", "On-premises only"], correctIndex: 1 },
];

const aiQuestions: MCQQuestion[] = [
  { question: "What is artificial intelligence?", options: ["A programming language", "Simulation of human intelligence by machines", "A database system", "A hardware component"], correctIndex: 1 },
  { question: "What is the Turing Test?", options: ["A coding challenge", "A test to determine if a machine can exhibit intelligent behavior", "A hardware benchmark", "A software testing method"], correctIndex: 1 },
  { question: "What is a neural network?", options: ["A computer network", "A computing system inspired by biological neurons", "A database structure", "A web framework"], correctIndex: 1 },
  { question: "What does NLP stand for?", options: ["Natural Language Processing", "Neural Logic Programming", "Network Layer Protocol", "Non-Linear Processing"], correctIndex: 0 },
  { question: "What is supervised learning?", options: ["Learning without data", "Learning from labeled training data", "Learning without labels", "Self-learning AI"], correctIndex: 1 },
  { question: "What is a decision tree?", options: ["A type of database", "A tree-shaped model for classification/regression", "A binary tree", "A file structure"], correctIndex: 1 },
  { question: "What is overfitting?", options: ["Model performs well on all data", "Model memorizes training data but fails on new data", "Model is too simple", "Model training is too fast"], correctIndex: 1 },
  { question: "What is backpropagation?", options: ["A search algorithm", "Algorithm to update neural network weights", "A data preprocessing step", "A sorting algorithm"], correctIndex: 1 },
  { question: "What is reinforcement learning?", options: ["Learning from labeled data", "Learning through rewards and penalties", "Learning from unlabeled data", "Transfer learning"], correctIndex: 1 },
  { question: "What is a CNN used for?", options: ["Text processing", "Image recognition and processing", "Database queries", "Network security"], correctIndex: 1 },
  { question: "What is transfer learning?", options: ["Moving data between servers", "Using a pre-trained model for a new task", "Transferring files", "Database migration"], correctIndex: 1 },
  { question: "What is an activation function?", options: ["A function that starts the program", "A function that determines neuron output", "A login function", "A sorting function"], correctIndex: 1 },
  { question: "What is gradient descent?", options: ["A mountain climbing algorithm", "An optimization algorithm to minimize loss", "A data visualization", "A search algorithm"], correctIndex: 1 },
  { question: "What is a GAN?", options: ["General Algorithm Network", "Generative Adversarial Network", "Guided Attention Network", "Graph Analysis Network"], correctIndex: 1 },
  { question: "What is computer vision?", options: ["Monitoring computers", "Enabling computers to interpret visual information", "A display technology", "A graphics card"], correctIndex: 1 },
  { question: "What is the difference between AI and ML?", options: ["They are the same", "AI is the broader concept; ML is a subset of AI", "ML is broader than AI", "AI is only for robots"], correctIndex: 1 },
  { question: "What is an epoch in neural network training?", options: ["A time period", "One complete pass through the training dataset", "A type of layer", "An activation function"], correctIndex: 1 },
  { question: "What is a loss function?", options: ["A function that measures model error", "A function that deletes data", "A sorting function", "A data loading function"], correctIndex: 0 },
  { question: "What is feature engineering?", options: ["Building hardware", "Creating/selecting relevant input variables for a model", "Debugging code", "Database indexing"], correctIndex: 1 },
  { question: "What is a transformer model?", options: ["An electrical device", "An attention-based neural network architecture", "A data transformer", "A sorting algorithm"], correctIndex: 1 },
];

const mlQuestions: MCQQuestion[] = [
  { question: "What is the difference between classification and regression?", options: ["No difference", "Classification predicts categories; regression predicts continuous values", "Classification is faster", "Regression uses neural networks only"], correctIndex: 1 },
  { question: "What is K-Nearest Neighbors (KNN)?", options: ["A clustering algorithm", "Classifies based on closest training examples", "A neural network", "A decision tree variant"], correctIndex: 1 },
  { question: "What is the bias-variance tradeoff?", options: ["A pricing model", "Balance between underfitting (bias) and overfitting (variance)", "A hardware consideration", "A data format"], correctIndex: 1 },
  { question: "What is cross-validation?", options: ["Validating passwords", "Technique to evaluate model by splitting data into folds", "A type of encryption", "Database validation"], correctIndex: 1 },
  { question: "What is a Random Forest?", options: ["A park", "An ensemble of decision trees", "A single decision tree", "A neural network"], correctIndex: 1 },
  { question: "What is the purpose of a confusion matrix?", options: ["To confuse the model", "To evaluate classification performance", "To encode data", "To visualize clusters"], correctIndex: 1 },
  { question: "What is PCA (Principal Component Analysis)?", options: ["A programming language", "Dimensionality reduction technique", "A sorting algorithm", "A database query"], correctIndex: 1 },
  { question: "What is the output?\n\nfrom sklearn.preprocessing import StandardScaler\nscaler = StandardScaler()\n# What does scaler.fit_transform(X) do?", options: ["Deletes data", "Normalizes data to mean=0, std=1", "Sorts data", "Encrypts data"], correctIndex: 1 },
  { question: "What is logistic regression used for?", options: ["Predicting continuous values", "Binary classification", "Clustering", "Dimensionality reduction"], correctIndex: 1 },
  { question: "What is a learning rate?", options: ["How fast a student learns", "Step size for updating model weights", "Data processing speed", "Model accuracy"], correctIndex: 1 },
  { question: "What is regularization?", options: ["Making data regular", "Technique to prevent overfitting by adding penalty", "Sorting data", "Normalizing inputs"], correctIndex: 1 },
  { question: "What is K-Means clustering?", options: ["A classification algorithm", "An unsupervised algorithm that groups data into K clusters", "A regression technique", "A neural network type"], correctIndex: 1 },
  { question: "What is precision in ML?", options: ["Model speed", "True positives / (True positives + False positives)", "Total accuracy", "Training time"], correctIndex: 1 },
  { question: "What is recall?", options: ["Memory usage", "True positives / (True positives + False negatives)", "Model size", "Processing time"], correctIndex: 1 },
  { question: "What is an SVM (Support Vector Machine)?", options: ["A virtual machine", "A classifier that finds the optimal hyperplane", "A storage system", "A neural network"], correctIndex: 1 },
  { question: "What is the purpose of train-test split?", options: ["To double the data", "To evaluate model on unseen data", "To encrypt data", "To sort data"], correctIndex: 1 },
  { question: "What is ensemble learning?", options: ["Learning one model", "Combining multiple models for better performance", "Data preprocessing", "Feature selection"], correctIndex: 1 },
  { question: "What is gradient boosting?", options: ["Making gradients faster", "Sequentially training models to correct predecessors' errors", "A data visualization", "A clustering method"], correctIndex: 1 },
  { question: "What does fit() do in scikit-learn?", options: ["Deletes the model", "Trains the model on data", "Predicts output", "Evaluates accuracy"], correctIndex: 1 },
  { question: "What is the F1 score?", options: ["A race car metric", "Harmonic mean of precision and recall", "Model training speed", "Data accuracy"], correctIndex: 1 },
];

const technologyQuestions: MCQQuestion[] = [
  { question: "What does API stand for?", options: ["Application Programming Interface", "Advanced Program Integration", "Application Process Interface", "Automated Programming Interface"], correctIndex: 0 },
  { question: "What is version control?", options: ["Controlling software versions", "System for tracking changes in code", "A type of database", "Hardware management"], correctIndex: 1 },
  { question: "What does Git do?", options: ["Hosts websites", "Distributed version control", "Compiles code", "Manages databases"], correctIndex: 1 },
  { question: "What is an algorithm?", options: ["A programming language", "A step-by-step procedure for solving a problem", "A data type", "A hardware component"], correctIndex: 1 },
  { question: "What is open source software?", options: ["Free hardware", "Software with publicly available source code", "Paid software", "Cloud software only"], correctIndex: 1 },
  { question: "What is an IDE?", options: ["Internet Development Environment", "Integrated Development Environment", "Internal Data Engine", "Interface Design Editor"], correctIndex: 1 },
  { question: "What is agile methodology?", options: ["A programming language", "An iterative approach to software development", "A database system", "A testing framework"], correctIndex: 1 },
  { question: "What is a compiler?", options: ["A text editor", "Translates source code to machine code", "A web browser", "A database tool"], correctIndex: 1 },
  { question: "What is TCP/IP?", options: ["A programming language", "Communication protocols for the internet", "A database", "An operating system"], correctIndex: 1 },
  { question: "What is encryption?", options: ["Deleting data", "Converting data to unreadable format for security", "Compressing data", "Sorting data"], correctIndex: 1 },
  { question: "What is a software framework?", options: ["Computer hardware", "A reusable set of tools/libraries for development", "An operating system", "A programming language"], correctIndex: 1 },
  { question: "What is Big O notation?", options: ["A programming language", "Describes algorithm efficiency/complexity", "A data structure", "An error type"], correctIndex: 1 },
  { question: "What is debugging?", options: ["Adding bugs", "Finding and fixing errors in code", "Writing code", "Deploying software"], correctIndex: 1 },
  { question: "What does OOP stand for?", options: ["Object-Oriented Programming", "Online Optimization Process", "Output Operation Protocol", "Ordered Object Processing"], correctIndex: 0 },
  { question: "What is a REST API?", options: ["A sleeping interface", "An architectural style for web services using HTTP methods", "A database system", "A programming language"], correctIndex: 1 },
  { question: "What is unit testing?", options: ["Testing hardware", "Testing individual components of code", "Testing the entire system", "Performance testing"], correctIndex: 1 },
  { question: "What is a stack overflow?", options: ["A website only", "When call stack exceeds its limit", "A type of sorting", "Memory leak"], correctIndex: 1 },
  { question: "What is the difference between HTTP and HTTPS?", options: ["No difference", "HTTPS is encrypted with SSL/TLS", "HTTP is faster", "HTTPS is older"], correctIndex: 1 },
  { question: "What is JSON?", options: ["A programming language", "JavaScript Object Notation — a data format", "A database", "An operating system"], correctIndex: 1 },
  { question: "What is a design pattern?", options: ["A UI design", "A reusable solution to common software problems", "A database schema", "A coding style"], correctIndex: 1 },
];

const javascriptQuestions: MCQQuestion[] = [
  { question: "What is the output?\n\nconsole.log(typeof null)", options: ["'null'", "'object'", "'undefined'", "Error"], correctIndex: 1 },
  { question: "What is the output?\n\nconsole.log(0.1 + 0.2 === 0.3)", options: ["true", "false", "Error", "undefined"], correctIndex: 1 },
  { question: "What does `===` check in JavaScript?", options: ["Value only", "Type only", "Value and type", "Reference only"], correctIndex: 2 },
  { question: "What is the output?\n\nlet x = [1, 2, 3];\nlet y = x;\ny.push(4);\nconsole.log(x.length)", options: ["3", "4", "Error", "undefined"], correctIndex: 1 },
  { question: "What is the output?\n\nconsole.log('5' - 3)", options: ["'53'", "2", "NaN", "Error"], correctIndex: 1 },
  { question: "What is the output?\n\nconsole.log('5' + 3)", options: ["8", "'53'", "NaN", "Error"], correctIndex: 1 },
  { question: "Which method creates a new array with results of calling a function on every element?", options: ["forEach()", "map()", "filter()", "reduce()"], correctIndex: 1 },
  { question: "What is the output?\n\nconst obj = {a: 1};\nObject.freeze(obj);\nobj.a = 2;\nconsole.log(obj.a)", options: ["1", "2", "Error", "undefined"], correctIndex: 0 },
  { question: "What is a closure in JavaScript?", options: ["A way to close the browser", "A function with access to its outer scope", "A type of loop", "A class constructor"], correctIndex: 1 },
  { question: "What is the output?\n\nconsole.log([...'hello'])", options: ["['hello']", "['h','e','l','l','o']", "Error", "undefined"], correctIndex: 1 },
  { question: "Fill in the blank to destructure:\n\nconst {name, age} = _____", options: ["{name: 'A', age: 1}", "[name, age]", "'A', 1", "name, age"], correctIndex: 0 },
  { question: "What does `async/await` do?", options: ["Makes code synchronous", "Handles promises more readably", "Creates threads", "Blocks the event loop"], correctIndex: 1 },
  { question: "What is the output?\n\nconsole.log(typeof NaN)", options: ["'NaN'", "'number'", "'undefined'", "'object'"], correctIndex: 1 },
  { question: "What is the output?\n\nconst arr = [1,2,3];\nconsole.log(arr.includes(2))", options: ["true", "false", "1", "Error"], correctIndex: 0 },
  { question: "What is hoisting in JavaScript?", options: ["Moving code to a server", "Variable/function declarations moved to top of scope", "A type of error", "CSS animation"], correctIndex: 1 },
  { question: "What is the output?\n\nlet a = 1;\nlet b = a++;\nconsole.log(a, b)", options: ["1 1", "2 1", "2 2", "1 2"], correctIndex: 1 },
  { question: "Which keyword declares a block-scoped variable?", options: ["var", "let", "global", "static"], correctIndex: 1 },
  { question: "What is the output?\n\nconsole.log([] == false)", options: ["true", "false", "Error", "undefined"], correctIndex: 0 },
  { question: "What does `Promise.all()` do?", options: ["Runs first promise", "Waits for all promises to resolve", "Cancels promises", "Creates a new promise"], correctIndex: 1 },
  { question: "What is the output?\n\nconst fn = () => arguments;\nconsole.log(fn(1,2))", options: ["[1, 2]", "ReferenceError", "{1, 2}", "undefined"], correctIndex: 1 },
];

export const mcqBank: Record<string, MCQQuestion[]> = {
  'Python': pythonQuestions,
  'Java': javaQuestions,
  'JavaScript': javascriptQuestions,
  'C++': cppQuestions,
  'Web Development': webDevQuestions,
  'Data Structures': dsaQuestions,
  'Database Systems': dbQuestions,
  'Cloud Computing': cloudQuestions,
  'Artificial Intelligence': aiQuestions,
  'Machine Learning': mlQuestions,
  'Technology': technologyQuestions,
  'Data Science': [...mlQuestions.slice(0, 10), ...aiQuestions.slice(0, 10)],
};

export function getQuestionsForCategory(category: string): MCQQuestion[] {
  const questions = mcqBank[category] || mcqBank['Technology'] || [];
  // Return exactly 20 questions, shuffled
  const shuffled = [...questions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, 20);
}
